name: veboost

plugins:
  - name: vyper
  - name: ens
  - name: etherscan
  - name: foundry
  - name: alchemy

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  base_fee: 0
  priority_fee: 0
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy